# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - TradingUpFundation

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a3331c6dbd904468ada33ca8337da446 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d834fdc9cd874a35bd30a11bf1a26c56 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a3331c6dbd904468ada33ca8337da446 }}/jamesacosta/front-trading:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'TradingUpFundation'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0c297960a9de4a29aca04d477673c776 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a3331c6dbd904468ada33ca8337da446 }}/jamesacosta/front-trading:${{ github.sha }}'